# Generated by Django 5.2.3 on 2025-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='last_download_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='total_download_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
